import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import { GoogleTagManager } from '@next/third-parties/google'
import { auth } from "@/auth";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <head>
        <GoogleTagManager gtmId="GTM-MLHH8B63" />
        {session?.user && (
          <Script id="user-gtm">
            {`
              window.dataLayer = window.dataLayer || [];
              window.dataLayer.push({
                user: ${JSON.stringify(session.user)}
              });
            `}
          </Script>
        )}
      </head>
      <body className={`${inter.className} relative`}>
        <SessionProvider session={session}>{children}</SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
